# -*- coding: utf-8 -*-
"""BIOINFORMATICS.ipynb

Automatically generated by Colab.

BIOINFORMATICS- Protein Sequence Property Analyzer
"""

#Install Dependencies
#!pip install biopython matplotlib

#Import Libraries
from Bio.SeqUtils.ProtParam import ProteinAnalysis
import matplotlib.pyplot as plt
import json
import re

#Provide FASTA Input
fasta_data = """>Stable_Hydrophobic_1
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
>Stable_Hydrophilic_1
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
>Unstable_Protein_1
PESTPESTPESTPESTPESTPESTPESTPESTPESTPESTPESTPEST
>Unstable_Protein_2
GPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGP
>Mixed_Protein_1
MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF
>Mixed_Protein_2
GAVLILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSR
>Hydrophilic_Rich
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
>Hydrophobic_Rich
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
"""

#FASTA Parser
def read_fasta_from_string(fasta_string):
    sequences = {}
    name = ""
    seq = ""

    for line in fasta_string.split("\n"):
        line = line.strip()
        if line.startswith(">"):
            if name:
                sequences[name] = seq
            name = line[1:]
            seq = ""
        else:
            seq += line

    if name:
        sequences[name] = seq

    return sequences

#Hydropathy (Sliding Window)
hydropathy_scale = {
    'A': 1.8, 'C': 2.5, 'D': -3.5, 'E': -3.5,
    'F': 2.8, 'G': -0.4, 'H': -3.2, 'I': 4.5,
    'K': -3.9, 'L': 3.8, 'M': 1.9, 'N': -3.5,
    'P': -1.6, 'Q': -3.5, 'R': -4.5, 'S': -0.8,
    'T': -0.7, 'V': 4.2, 'W': -0.9, 'Y': -1.3
}

def sliding_window_hydropathy(sequence, window=5):
    values = []
    for i in range(len(sequence) - window + 1):
        segment = sequence[i:i+window]
        score = sum(hydropathy_scale[aa] for aa in segment) / window
        values.append(score)
    return values

#Motif Detection
def find_motifs(sequence, motif="N[^P][ST]"):
    return [m.start() for m in re.finditer(motif, sequence)]

#Protein Analysis
def analyze_protein(sequence):
    protein = ProteinAnalysis(sequence)

    helix, turn, sheet = protein.secondary_structure_fraction()

    return {
        "length": len(sequence),
        "molecular_weight": protein.molecular_weight(),
        "pI": protein.isoelectric_point(),
        "gravy": protein.gravy(),
        "instability_index": protein.instability_index(),
        "secondary_structure": {
            "helix": helix,
            "turn": turn,
            "sheet": sheet
        },
        "hydropathy_profile": sliding_window_hydropathy(sequence),
        "motifs": find_motifs(sequence)
    }

#Classification Model
def classify_protein(instability_index, gravy):
    if instability_index < 40 and gravy > 0:
        return "Stable & Hydrophobic"
    elif instability_index < 40:
        return "Stable & Hydrophilic"
    else:
        return "Unstable Protein"

#Visualization
def plot_hydropathy(values, name):
    plt.figure()
    plt.plot(values)
    plt.title(f"Hydropathy Plot - {name}")
    plt.xlabel("Position")
    plt.ylabel("Hydropathy")
    plt.show()

#Main Execution
sequences = read_fasta_from_string(fasta_data)

all_results = {}

for name, seq in sequences.items():
    print(f"\n Analyzing {name}...")

    result = analyze_protein(seq)

    classification = classify_protein(
        result["instability_index"],
        result["gravy"]
    )

    result["classification"] = classification
    all_results[name] = result

    # Print results
    print(f"Length: {result['length']}")
    print(f"Molecular Weight: {result['molecular_weight']:.2f}")
    print(f"Isoelectric Point: {result['pI']:.2f}")
    print(f"GRAVY: {result['gravy']:.2f}")
    print(f"Instability Index: {result['instability_index']:.2f}")
    print(f"Motif Positions: {result['motifs']}")
    print(f"Classification: {classification}")

    # Plot graph
    plot_hydropathy(result["hydropathy_profile"], name)

"""this shell give output here itself"""

import pandas as pd

# Convert results into table format
table_data = []

for name, result in all_results.items():
    row = {
        "Protein": name,
        "Length": result["length"],
        "Molecular Weight": round(result["molecular_weight"], 2),
        "pI": round(result["pI"], 2),
        "GRAVY": round(result["gravy"], 2),
        "Instability Index": round(result["instability_index"], 2),
        "Helix": round(result["secondary_structure"]["helix"], 2),
        "Turn": round(result["secondary_structure"]["turn"], 2),
        "Sheet": round(result["secondary_structure"]["sheet"], 2),
        "Motifs Found": len(result["motifs"]),
        "Classification": result["classification"]
    }
    table_data.append(row)

# Create DataFrame
df = pd.DataFrame(table_data)

# Display table
df

"""this shell gives output in file format in the left panel .json format"""